### ISSUE TITLE
Настройки. Отправлять только изменения.

### ISSUE THREAD

**Issue by Oleg-Sob** [alidonet/gc97_esp#11]
В настройках если ставишь галочку "Отправлять только изменения" , данные передаются все и  всегда, а если снять галочку то данные передаются когда изменены. Оно вроде как и не ошибка, но работает наоборот.

**Comment by alidonet** [comment]
Проверю. Спасибо.

**Comment by alidonet** [comment]
Опция должна работать. Есть несколько моментов:

1. Данные разбиты на пакеты: ESP, GC97. Данные ESP почти всегда отправляются: меняется аптайм контроллера, уровень сигнала. По GC97 могут быть пропуски.
2. Даже если данные не обновлялись, то раз в 3-5 опросов данные будут отправляться на сервер в любом случае, даже просто с целью подтверждения соединения и чтобы дать серверу знать, что мы еще живы и подключены :)

Обычно, на реальных подключениях данные шлются на каждый опрос кулонометра, поэтому опция чисто номинальная.
