### ISSUE TITLE
sensor.gc97_meter_capacity

### ISSUE THREAD

**Issue by Oleg-Sob** [alidonet/gc97_esp#12]
Выдаёт ошибку 
Entity sensor.gc97_meter_capacity (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'Ah' which is not a valid unit for the device class ('energy') it is using; expected one of ['Wh', 'GJ', 'MWh', 'MJ', 'kWh'];

Нужно убрать device class ('energy')

**Comment by alidonet** [comment]
Исправлено в 240504
