### ISSUE TITLE
Не отключается WiFi точка от ESP.

### ISSUE THREAD

**Issue by Pro-Bizz** [alidonet/gc97_esp#14]
В настройках отключил WiFI сеть, но ESP почему-то продолжается вещать WiFi.
Прошивка - [ver. 240612.mg]

![img-2024-06-25-15-28-55](https://github.com/alidonet/GC97_ESP/assets/152051325/30057ffa-80b1-4504-8535-00b10557d15b)
![img-2024-06-25-15-29-04](https://github.com/alidonet/GC97_ESP/assets/152051325/4211aab5-5c6f-4dfe-a2ee-18a6cc086fd9)
![img-2024-06-25-15-30-29](https://github.com/alidonet/GC97_ESP/assets/152051325/711c86c1-56d3-46da-b5eb-8f0aa3dfaf49)

**Comment by alidonet** [comment]
Я так понимаю, вопрос про отключение точки доступа? Проверьте, есть ли подключение ESP к WiFi? Если соединения не будет, то точка доступа включится автоматически, иначе контроллер не будет доступен по сети.
Если включена опция "Отключать когда есть Wi-Fi соединение", то точка доступа будет автоматически отключена спустя 3-4 минуты после успешного подключения к WiFi и если не будет активных соединений (подключенных к точке доступа клиентов).

**Comment by Pro-Bizz** [comment]
В том что и дело, ESP подключен к WiFi(2 скрина с настройками это доступ на WEB из локальной сети) и при этому они вешают точку в эфир с именами ESP-6E2***.

**Comment by Pro-Bizz** [comment]
Вот они подключены по WiFi:
![img-2024-06-26-10-57-45](https://github.com/alidonet/GC97_ESP/assets/152051325/2cd5a690-9800-4391-9ef2-6e15eaa01121)

Доступны локально:
![img-2024-06-26-10-59-00](https://github.com/alidonet/GC97_ESP/assets/152051325/7f262b37-b4df-461a-82cc-9361f80c434a)

И на них же работает точка доступа:
![img-2024-06-26-11-00-19](https://github.com/alidonet/GC97_ESP/assets/152051325/98d88820-ce3c-41bf-9e06-bc523fb32b07)

**Comment by alidonet** [comment]
@Pro-Bizz  Спасибо за отчет. Будем смотреть и наблюдать. 
В целом я заметил, что wifi соединение на ESP работает довольно нестабильно, что можно заметить по логам. Может быть это является причиной, почему поднимается периодически точка доступа. 
Попробуйте оставить опцию "Точка доступа активна" включенной, включить "Отключать когда есть Wi-Fi соединение" и перезагрузить контроллеры. По идее, после ребута точка поднимется и 3-4 минуты и потом будет отключена. Еще можно понаблюдать время соединения (судя по скриншотам у вас Кинетики, где есть детальная информация) -- как отличается время аптайма контроллера и указанное время соединения в информации от роутера. Также немного смущают скорости подключения (2 и 6 Мбит на скриншотах), при этом сносный уровень сигнала. Если это не искусственное ограничение, то немного странно -- обычно скорости в районе 65МБит, плюс/минус :) Да еще и соединение по 802.11**b**. Если у вас нет реальной необходимости в поддержке стандарта **b**, а тем более таких очень древних устройств в сети -- пробуйте использовать на роутере как минимум **g/n** для беспроводных подключений.

**Comment by Pro-Bizz** [comment]
Это что касаемо времени подключения.
![img-2024-06-26-13-44-58](https://github.com/alidonet/GC97_ESP/assets/152051325/869804b4-3203-4542-a1b2-24a1a8473020)
![img-2024-06-26-13-47-54](https://github.com/alidonet/GC97_ESP/assets/152051325/2908c0f2-03fe-4287-9c92-9fb218eabbf5)
Uptime: 7.02:06 на первом устройстве и Uptime: 7.02:06 на втором.

Да маленькую скорость подключения я видел, это не искусственное ограничение, это оно само так. Очень давно было выставного b/g/n, уже не помню почему. Сейчас пока переключить на g/n не могу, так как объект удаленный, если что-то не заведется - некому будет ребутнуть.

Сделал: _Попробуйте оставить опцию "Точка доступа активна" включенной, включить "Отключать когда есть Wi-Fi соединение" и перезагрузить контроллеры._ 
И ESP перестала светить свою точку доступа в сеть.

**Comment by alidonet** [comment]
Да, видно что переподключалась сеть, но временной промежуток большой, явно более 5 минут.
Я так понял, сейчас точка доступа отключена, как и ожидалось, но при этом контроллер успешно подключен к сети через wifi? Т.е. с ним есть связь.
Понаблюдайте еще немного, а я при случае гляну код. Он там уже порядком требует рефакторинга :)

**Comment by Oleg-Sob** [comment]
Поставьте галочку, Точка доступа активна, и всё будет работать
