### ISSUE TITLE
Message "Wrong Package (Size less tha expected)"

### ISSUE THREAD

**Issue by syrusfem** [alidonet/gc97_esp#15]
hi, i set up a new GC97 , the esp32 is configured , the webpage is up and i could configure all the settings, it connect to my Wifi and seem to see the mttq server but there is a message "Wrong Package (Size less tha expected)" in the webpage and there is no data from the GC97 on the webpage . it could be a bad soldering or a problem with the esp32 board?
![Screenshot 2024-08-25 074605](https://github.com/user-attachments/assets/547e709a-1e41-4d97-b4ee-3a6f60a4f017)

**Comment by alidonet** [comment]
@syrusfem Yes, very probably, this is a wrong connection between the ESP and GC97 boards. Check the TX/RX pairs. Also, sometimes the 2K resistance on RX line can be shortened (no guarantee on that action):

![изображение](https://github.com/user-attachments/assets/d70a416b-4dd6-4595-8281-731e3435a3da)

**Comment by syrusfem** [comment]
thanks i have reoldered the short on 2k resistance and the problem is resolved!

Another question: this is the second GC97 i am setting up , but the name is seen as the same from homeassistant (i think it broadcast a fixed name) and this confuse the data on homeassistant (it confuse the data of the 2 sensors) there is a way to change che name of  CG97 to another?
![Screenshot 2024-08-28 184051](https://github.com/user-attachments/assets/c8b210f9-4eb6-4c8c-9c86-32f96a55bbd3)

**Comment by alidonet** [comment]
Change the **`MQTT Topic`** name in the MQTT settings: it must be unique for each device.

**Comment by syrusfem** [comment]
Hi i tried renaming the MQTT name but even renaming the old GC97 and then reconnecting the new or renaming after the system see the two sensors result in only one set of data from one sensot to appear, and the first connected "capture" all sensors name even if the renamed sensor was not the same. so one set of data from one sensor (the first that is connected after a homeassistant reboot) goes good , the other sensor have no data captured and the data goes from the first sensor connected . So maybe it is a problem of how Mqtt work  but i cant find a way to have 2 set of data from 2 sensors appear in homeassistant.

**Comment by alidonet** [comment]
@syrusfem  Use unique MQTT topic on each device. Try to reboot ESP after the making a changes and wipeout your "GC97" objects in the HA.

**Comment by syrusfem** [comment]
yes i tried that too, changed name of devices  rebooted the devices, deleted original and new GC97 in HA but no results. i'll retry but HA see the 2 differently named GC97 every time but the first that connect with HA have data exposed the second none even if it is see in Mqtt so the values are passed but seem as HA accept only one device .

**Comment by syrusfem** [comment]
ok, redone all , changed MQTT topic , rebooted and after that set the MQTT communication with homeassistant and rebooted, same problem , MQTT see the monitoring device but the info are not exposed (even the IP of the device is not exposed) only difference is that a single info is present: battery energy (i think it is the total kwh of the battery) it is a info that i have not exposed on the other GC97 so maybe the sensors have the same name even with different topic and that is the problem? all other data is not  passed or homeassistant did not expose it. Only difference from the two ESP is that the old have an old firmware but it work so i don t think that is the problem.
only thing i have not used is the option: "Retain Flag Enabled" could be useful? i don't know the function.

i have attached the mqtt diagnostic the topic from the two sensors is different so that is correct.
[working sensor mqtt diagnotic.json](https://github.com/user-attachments/files/16823562/working.sensor.mqtt.diagnotic.json)
[not working sensor mqtt diagnostic.json](https://github.com/user-attachments/files/16823563/not.working.sensor.mqtt.diagnostic.json)


![3](https://github.com/user-attachments/assets/4a7ca7ca-e7e4-4b3e-b317-f5527924ef01)
![1](https://github.com/user-attachments/assets/f06d417e-c602-41f8-a13b-2ec0d70e8fec)

![5](https://github.com/user-attachments/assets/bfa6c095-e670-442f-a34c-7eabc0076aea)
![4](https://github.com/user-attachments/assets/fcb600d2-7f74-4eb6-9819-71c75e096f1e)

**Comment by syrusfem** [comment]
sorry for all the messages, i know that your is a work of passion so if there is no solution no problem for me. Just another bit of info, restarting HA has redone the problem where there is a swap of sensor readiongs from the 2 sensors, i post here the error in HA , it seems as even with different MQTT  topic HA recognise the data as the same from the two sensors. 
![error riavvio ha](https://github.com/user-attachments/assets/8cd3121c-d4e4-4b57-8090-5054aef741c4)

**Comment by alidonet** [comment]
I'll check it, but a little bit later. Just I don't have a test instance for now.

**Comment by syrusfem** [comment]
> I'll check it, but a little bit later. Just I don't have a test instance for now.

thanks!

**Comment by syrusfem** [comment]
Question: could i extract data from the webpage of the GC-97? It could bypass the need of mqtt data.

**Comment by alidonet** [comment]
@syrusfem  You can use the json data. Why need to parse the webpage itself? It's just a static page that loads json and render it. Check the documentation for details.

**Comment by syrusfem** [comment]
thnks using dev tools of chrome i found json values here: http://192.168.1.18/get/all.json  .

**Comment by alidonet** [comment]
@syrusfem 

    http://<ip_address>/get/all.json -- whole data package
    http://<ip_address>/get/gc97.json -- GC97 data only
    http://<ip_address>/get/esp.json -- ESP state data
    http://<ip_address>/get/state.json -- ESP uptime, common state.

**Comment by syrusfem** [comment]
thanks, capturing json data to HA sensor is as good as mqtt for meand it work good!
