### ISSUE TITLE
не стає місця для дод. символів

### ISSUE THREAD

**Issue by Nik8530** [alidonet/gc97_esp#3]
Вітаю.
В налаштуваннях mqtt не стає місця для вводу одного символу _broker.hivemq.co **broker.hivemq.com**_
чи можливо якось це виправити?

А така ж ситукація із _SSID Name_  моя назва банально не помістилася.

**Comment by alidonet** [comment]
Дякую за зворотний зв'язок. Перевіримо, по можливості виправимо.

**Comment by alidonet** [comment]
Вибачте за довгу відповідь. В оновленій версії збільшені поля для налаштувань. На жаль, після оновлення прошивки необхідно буде заново все налаштувати, включаючи точку доступу.
