### ISSUE TITLE
The SSID password has a maximum of 16 characters

### ISSUE THREAD

**Issue by marfi44** [alidonet/gc97_esp#4]
Is it possible to increase the SSID password field to 24 characters?

**Comment by alidonet** [comment]
@marfi44 Please check the new firmware (230523 and later)

**Comment by marfi44** [comment]
Thank you for the quick response to changing the length of the SSID 
password. However, the new version 230523 is unstable. After uploading 
the firmware and connecting to IP: 192.168.4.1, the connection still 
disconnects after 2-3 seconds. Tested on D1 mini and D1 mini PRO boards 
with the same result (ver.230419-client will be displayed on the WEB 
page). The previous version 230420 runs correctly on both boards.

marfi44


Dňa 23. 5. 2023 o 8:57 Alexander napísal(a):

**Comment by alidonet** [comment]
Will check it

**Comment by alidonet** [comment]
@marfi44 As a workaround, you can use version 230523 to set up a right one SSID and after that perform the firmware rollback to the previous, stable version. The old version could work without any issues with a long SSID. 
In fact, I didn't make any changes for the code itself, only for the main web-page, so I don't know that can be a reason for unstable work. In any case, I'll check it. Thanks for feedback.

**Comment by marfi44** [comment]
The problem is the web-page itself (version 230523). At start-up, it won't hold the connection long enough for me to write out and send the SSID data. The old version is OK. Even the connection with the new web-page is problematic. It does not start immediately. I have to initialize it several times. The display image remains gray, not green with data, as in the previous version. The other pages are not pre-filled either (MQTT, port, ...). The WiFi connection (192.168.4.1) only manages to connect for a few seconds, then disconnects and can be reconnected for maybe 10 tries. And it is possible to connect to the web-page only sporadically.

**Comment by alidonet** [comment]
@marfi44 I guess, it was a problem with build the firmware. I re-assembly the code and pushed it as 230525 (instead of 230523). Please try that version and let me know. 
In case of issues, please send me details from the serial port logs (19200 baud speed), if this is possible for you. Thank you.

**Comment by marfi44** [comment]
I tried the new firmware version 230525 with the same result. After uploading the firmware and connecting via WiFi to the AP 8266, the connection is maintained for about 2-3 seconds. Then it falls off and it is possible to connect again maybe in 20 attempts, but also only for a short time. All fields in the web page - Settings are empty.
GC97-xxxx and ESPxxx are shown as APs (ESPxxx cannot be connected here). I'm trying it without connecting to the GC97.
[D1_mini.txt](https://github.com/alidonet/GC97_ESP/files/11567638/D1_mini.txt)
[D1_mini_Pro.txt](https://github.com/alidonet/GC97_ESP/files/11567647/D1_mini_Pro.txt)
![2023-05-25 184531](https://github.com/alidonet/GC97_ESP/assets/93874160/b0def532-b4d4-4e96-b42d-49b92f06d124)
![2023-05-25 185214](https://github.com/alidonet/GC97_ESP/assets/93874160/38aa8c3a-051c-407a-b7e2-c8070bc1514b)
![2023-05-25 190221](https://github.com/alidonet/GC97_ESP/assets/93874160/5e98ae3e-9b8e-45c9-8161-8b67a7a0ca89)
![2023-05-25 190726](https://github.com/alidonet/GC97_ESP/assets/93874160/20d1ae66-ba12-4d31-98b1-382f14635d48)
![2023-05-25 154828](https://github.com/alidonet/GC97_ESP/assets/93874160/b7023a51-46d2-4794-ab26-ff684ab2cf1b)

**Comment by alidonet** [comment]
@marfi44 Thanks for feedback with logs: it's crashing and reboot due to RTE. I'll investigate it more and try to reproduce/fix it.

**Comment by alidonet** [comment]
@marfi44 As a workaround: use the latest stable version [230420](https://github.com/alidonet/GC97_ESP/tree/main/bin/previous/230420) and try to setup the settings manually as requests: 
`http://192.168.4.1/cmd/options?ssid=**SSID**&ssid_psw=**PSW**`
where you need to replace \*\*xxx\*\* parts with your credentials.
Please note that in case of saving the settings via web UI you'll probably need to do this request again since the SSID can be truncated. So you can set all other settings and update the SSID manually at the end.

**Comment by alidonet** [comment]
@marfi44 Please check the recent version, [230526](https://github.com/alidonet/GC97_ESP/blob/main/bin/GC97_ESP.bin).

**Comment by alidonet** [comment]
😎
