### ISSUE TITLE
Не верное отображение температуры.

### ISSUE THREAD

**Issue by Pro-Bizz** [alidonet/gc97_esp#5]
Приветствую!
Как только температура принимает отрицательное значение, температура начинает отображаться как "temp": 6553.1
![img-2023-11-26-09-22-19](https://github.com/alidonet/GC97_ESP/assets/152051325/00437774-bcfb-4cfa-8511-9b4ecd95256a)

**Comment by alidonet** [comment]
@Pro-Bizz  Спасибо, что нашли такой баг. Исправим :)

**Comment by alidonet** [comment]
@Pro-Bizz Пожалуйста, попробуйте эту прошивку: https://github.com/alidonet/GC97_ESP/blob/main/bin/GC97_ESP.bin
Буду благодарен, если сообщите о результатах.

**Comment by Pro-Bizz** [comment]
Прошил удаленное устройство и потерял к нему доступ. Оно почему-то свалилось в режим AP, вижу в эфире GC97-ХХХХ но подключиться к тему не могу. Буду на месте, тогда дам обратную связь.

**Comment by alidonet** [comment]
Да, неприятная ситуация. Я попробовал прошиться с последней стабильной прошивки на эту тестовую, по воздуху -- не смог воспроизвести проблему. Возможно, каким-то образом слетели настройки или был сбой при обновлении. 
Не помните, было ли сообщение об удачной прошивке в виде "_Update Success! Rebooting..._"?

**Comment by Pro-Bizz** [comment]
До обновления на тестовую прошивку у меня стояла [ver. 230526.lg].
Когда я нашел этот проект была актуальная прошивка [230526], но при заливке .bin в esp были какие-то проблемы, я уже не помню какие. Поэтому я тогда установил вроде бы 230419 на ней еще после установки нужно было подгружать файлы веб сервера, и уже после через веб обновлялся до 230526.

И да, при обновлении на тестовую была надпись "Update Success! Rebooting..."?

**Comment by alidonet** [comment]
@Pro-Bizz Подскажите, удалось ли проверить новую прошивку?

**Comment by Pro-Bizz** [comment]
Буквально вчера настроил, а точнее по шнурку залил прошивку [ver. 231130.u] и подождал пока температура опустится. Отображается корректно.
![img-2023-12-05-11-33-13](https://github.com/alidonet/GC97_ESP/assets/152051325/7bfb1430-a278-43e2-a47d-ceea10f6eb19)

**Comment by alidonet** [comment]
@Pro-Bizz Спасибо за обратную связь и помощь в тестировании :)
