### ISSUE TITLE
Не передаются данные по MQTT после переподключения к Wifi.

### ISSUE THREAD

**Issue by vik021** [alidonet/gc97_esp#8]
Добрый день.
Замечена такая проблема - после переподключения по Wifi, например, после перезагрузки маршрутизатора, перестают передаваться данные на MQTT брокер. Решается только перезагрузкой ESP.

На данный момент решаю проблему с помощью удаленной перезагрузки ESP системой мониторинга через WEB запрос (http://<ip_address>/cmd/reset).

**Comment by alidonet** [comment]
@vik021 Проблема ясна. Попробую исправить в следующем обновлении прошивки.

**Comment by vik021** [comment]
Добрый день.
После крайнего обновления начал сыпать странные данные в mosquitto:
![изображение](https://github.com/alidonet/GC97_ESP/assets/34021686/a5400b26-529e-49c1-8b33-b30cc7b17155)

**Comment by alidonet** [comment]
Текущую прошивку (240317) не могу рекомендовать как стабильную. Но в ней я попытался исправить некоторые проблемы.
Самое главное -- должно переподключаться к MQTT в случае проблем (обычно в пределах 2-3 минут).
Но еще, что является breaking changes, поменялись немного данные MQTT: были просьбы отдавать json и отдельно данные. А также могут быть более 1 кулонометра в сети/обрабатываться на сервере. Поэтому немного изменена логика именования топиков под корневым gc97 (имя настраиваемо): использованы префиксы. Скорее всего, вам надо будут скорректировать пути к данным.
![изображение](https://github.com/alidonet/GC97_ESP/assets/7659676/4e11e8e5-6061-4d15-8d65-57ece5640f34)
При этом должны сохраняться все топики вне зависимости от опции "hass discovery", чего раньше не было.

**Comment by vik021** [comment]
Спасибо. Уже понял, что дело в именовании топиков.

**Comment by vik021** [comment]
Есть еще вопрос не по теме, рискну задать его здесь. )
У меня к системе подключен автоинвертор 12-220, от которого питается холодильник, но при включении холодильника начинают прыгать показания на gc97 видимо из-за помех, кто-нибудь сталкивался с таким? Есть какие-то пути решения данной проблемы?

**Comment by alidonet** [comment]
А как именно выражается "прыгание"? Какие отклонения в показаниях?
Тут вариантов может быть много, от реальных изменений до помех по питанию, например, когда БП или DC-DC низкого качества.

**Comment by vik021** [comment]
> А как именно выражается "прыгание"? 

Показания скачкут кардинально, от плюса к минусу раз в 1-2 секунды, после чего соответсвенно доверять показаниям кулонометра нет смысла. Пока такое замечено только при подключении данного устройства-холодильника (ледогенаератора). В принципе много отзывов по GC97 от том, что скачут показания. Но вот нигде не нашел решения, как это победить. Думал, что меня эта проблема обойдет, так как инвртор чистый синус, но к сожалению не повезло.

![изображение](https://github.com/alidonet/GC97_ESP/assets/34021686/269c700a-8fc9-43a7-8e0c-90f98b77c43e)

**Comment by alidonet** [comment]
На самом деле, при получении данных от кулонометра, в коде с небольшой задержкой происходит тройной опрос и после этого отдаются усредненные данные. Это, в первую очередь сделано для избавления от мелкого "дрожания" показаний при относительно стабильных показаниях. По идее, конечно, резкие всплески как-то надо фильтровать, но тут общей рекомендации вряд ли можно найти.

**Comment by alidonet** [comment]
Изначальная проблема должна быть исправлена. Не реже чем раз в 3 минуты будет попытка повторного подключения.

**Comment by vik021** [comment]
> Изначальная проблема должна быть исправлена. Не реже чем раз в 3 минуты будет попытка повторного подключения.

Добрый день. Проблемы больше  не наблюдал. Спасибо
