### ISSUE TITLE
Данные переходят в состояние недоступно

### ISSUE THREAD

**Issue by Oleg-Sob** [alidonet/gc97_esp#9]
Каждые 2-3 минуты данные переходят в состояние недоступно, потом восстанавливаются. Получаю через MQTT в Home Assistant  . Прошивка залита в Node Mcu на ESP 8266. Менял ESP увеличивал время опроса, не помогает. Подскажите в чём дело ?

![97](https://github.com/alidonet/GC97_ESP/assets/71137109/14269ac7-dcad-4c06-8d46-d21a1287915a)

**Comment by alidonet** [comment]
@Oleg-Sob Есть возможность отследить в консоли, что происходит?

**Comment by Oleg-Sob** [comment]
Ошибок нигде не выдаёт, просто впечатление что данные не проходят через RX TX. Подсоединил напрямую до резисторов.

**Comment by Oleg-Sob** [comment]
Может стоит попробовать после резисторов подключить RX TX ?

**Comment by alidonet** [comment]
@Oleg-Sob Резистор зануляли? https://youtu.be/SesL8hBFKQ0?t=858

**Comment by Oleg-Sob** [comment]
Я подпаялся сразу после резисторов, до резисторов вообще не передаются данные.

![9777](https://github.com/alidonet/GC97_ESP/assets/71137109/e17f7077-c29b-4df4-9c4b-dd8be935ec76)

**Comment by alidonet** [comment]
@Oleg-Sob Посмотрите все же в консоли: если будут проблемы именно с получением данных от GC97, то в логах это будет видно и будет стоять [x] GC97
Потом уже можно будет посмотреть, что уходит по MQTT
Как вариант, можно временно отключить опцию "Отправлять только изменения":
![manual_options_misc](https://github.com/alidonet/GC97_ESP/assets/7659676/37ff80d5-9940-46cb-89a7-58938bc134b2)

**Comment by Oleg-Sob** [comment]
Вы в какой консоли имеете ввиду посмотреть ? Опцию "Отправлять только изменения" я отключал, не помогло.

**Comment by Oleg-Sob** [comment]
Смотрел через MQTT Explorer. Состояние esp_problem = off меняет на esp_problem = on  и esp_message = GC97 is OK на esp_message = GC97 not connected, meter_status = online на meter_status = offline

**Comment by Oleg-Sob** [comment]
Убрал HASS авто-обнаружение, создал сам датчики и они работают нормально. Это что то с автообнаружением.

**Comment by alidonet** [comment]
@Oleg-Sob Немного неожиданно решилась проблема. Спасибо за информацию, буду следить: функция HASS discovery относительно новая в коде, может где-то проблема с ней.
А про консоль я имел ввиду обычную консоль, которая слушает COM-порт: туда во время работы контроллера выдается сервисная информация на загрузку и состояние каждые несколько секунд.

**Comment by Oleg-Sob** [comment]
Если будут изменения в прошивке HASS discovery , буду рад потестировать, пока останусь на созданных датчиках, если не тяжело, подскажите как создать датчик "Charging" по MQTT передаётся true false, если бы было on off было бы проще

**Comment by alidonet** [comment]
Можете пока создать вручную датчик на основе существующего.
Насчет прошивки пока придется подождать: у меня сам кулонометр пока вне доступа, а без него именно этот функционал неэффективно будет тестировать.

**Comment by Oleg-Sob** [comment]
true false датчики не понимают, они понимают on off

**Comment by Oleg-Sob** [comment]
В прошивке 240317 всё работает нормально, данные не пропадают.
